import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { About, Header, Skills } from '../container'
import { Navbar,Footer } from '../components'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Devansh Lodhi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className='app_Main'>
      <Navbar/>
        <Header/>
        <About/>
        <Skills/>
      
      <Footer/>

      </div>
       
    </>
  )
}
